### ISSUE TITLE
Disable anonymous file browsing

### ISSUE THREAD

**Issue by cpw** [dzikoysk/reposilite#435]
Would like a config option to disable the anonymous file browser if possible and only allow authenticated browsing... obviously, serving files themselves should still work anonymously.

**Comment by dzikoysk** [comment]
Yeah, I had this option in the past, but support was dropped when I implemented private repositories. I'll take a look on that in Reposilite 2.10.x due to some related issues.

**Comment by LexManos** [comment]
Is there a simple method we can do that flat out disables the web interface for the time being? Currently you read the index.html and app.js from the resources in the jar. Any chance this can be moved to a config file on disc. So at the very least we can 'disable' it by supplying a empty index.html. That'd work for us for the time being.

**Comment by dzikoysk** [comment]
Atm the best option could be a fork as long as it won't be an option in official repository 🤔

**Comment by LexManos** [comment]
Ya, that's what I figured. Consider this a additional request to this config option. The ability to customize the frontend without rebuilding the image.

**Comment by LexManos** [comment]
Alright, was able to Fork and figure out how to build, debug, and test the main backend project.
Came up with this: https://github.com/MinecraftForge/reposilite/commit/2cb4f75877b657b436b01953d8d3488fde825b85
With the API shut down the main page still shows up, but nothing gets listed. You can still login to the dashboard and then walk everything like normal.
I want to look into how to build/test the frontend, do you have any documentation, or suggestion for any IDEs or anything to work with that? I've never worked with vue before.

**Comment by dzikoysk** [comment]
You can just run `mvn clean install` and you will get the final jar file in `target` directory. To build/run frontend, you need to use start `npm install`  in frontend directory to fetch all of the required dependencies. Then you can run it with `npm run serve`:

https://github.com/dzikoysk/reposilite/blob/f790a7c0f3edea07f66605a1888d311f79dbd9e8/reposilite-frontend/package.json#L6
 
I use VSC to develop frontend, but you can use whatever you want. Atm I'm commiting only small improvements due to a huge #387 fs rewrite. Speaking of your proposals:

* This issue addresses anonymous browsing and I'll add a proper way of disabling it in the future (probably through #394)
* Thinking about access tokens like about users is kinda misunderstanding of the model. Reposilite used user based system with projects and permissions in the past, but it does not really work well and it is not as safe as per repository access token. On the other hand I fully agree that the current implementation could be improved. If you're interested in proposing some changes in this area, I think we should move this part of a conversation to a new issue to keep it clean.
